/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;

@class AVTAvatarInstance;

@interface AVTPuppet: NSObject
+ (id)_pathForPuppetNamed:(id)arg1 inAvatarBundle:(bool)arg2;
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
@end
