/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;
#import "AVTAvatarView.h"

@interface AVTPuppetView: AVTAvatarView
@end
